"""
Module for testing behaviour of the music memory modules. Ideally tests should check for
expected results & also test against the results generated by existing code.
"""

import logging
import os
import os.path

import music_memory
